### ISSUE TITLE
Publish package to pypi

### ISSUE THREAD

**Issue by rzr** [Leiaz/python-awox-mesh-light#16]
I didnt see it at:
https://pypi.org/search/?q=awox
Please also tag versions,
I can help if you want to automate CD/CI or get inspiration from thoses changes:

https://github.com/rzr/awox-mesh-light-webthing/commit/2bd9d197ea876670e2c647882d42e7db50b66791

https://github.com/rzr/awox-mesh-light-webthing/commit/2bd9d197ea876670e2c647882d42e7db50b66791

https://github.com/rzr/awox-mesh-light-webthing/commit/a7134d1e8a27b9d6b9eb29992912ef5e230b0a66

Then I'll depend on yours

Thanks

**Comment by rzr** [comment]
please also check:

https://github.com/advisories/GHSA-6528-wvf6-f6qg

**Comment by rzr** [comment]
https://pypi.org/project/awoxmeshlight/

Excellent

**Comment by Leiaz** [comment]
I didn't publish it because I was not sure I'd keep the functions as they are, for instance for brightness I pass the rough value, between 0xa and 0x64 but maybe it would make more sense to pass a percentage for instance ... And I wanted to add getting the status from the light in a "nice" way. And in fact it should likely be the status of the lightS because they form a mesh ...
It is also lacking some functions ... 
I wanted to complete it a bit more, but then I have been away from the apartment where I had installed the light ...
